### ISSUE TITLE
roadmap: implemented system calls and API families

### ISSUE THREAD

**Issue by treeswift** [treeswift/libfatctl#1]
## Extended descriptor semantic
- [x] custom `fd`->`HANDLE` mapping
- [x] custom `HANDLE`->`fd` registration

## Extended descriptor contract
- [x] `fcntl` (FD_CLOEXEC)
- [ ] `fcntl` (status flags)
- [x] `fcntl` (duplication)

## Extended file attributes

`(get|set|etc.)xattr` withdrawn into `libxxxattr`

## Link API
- [x] `link`
- [x] `symlink`
- [x] `readlink`
- [x] `lstat`

## `dirfd` API
- [x] open (O_DIRECTORY)
### `DIR*` API
- [x] fdopendir
### `AT_*` API
- [x] `AT_*` constants
- [x] `openat`
- [x] `mkdirat`
- [x] `renameat`
- [x] `unlinkat`
- [x] `linkat`
- [x] `symlinkat`
- [x] `readlinkat`
- [x] `fstatat`

## I/O API
- [x] `dprintf`
- [x] `vdprintf`

## Lock API
- [ ] `flock`
- [ ] `fcntl` (struct flock)

## Notifications
`poll`/`select`/`notify` withdrawn into `libchoreo`

## Access rights
- [x] `faccessat`

### Ownership
`[f|l]chown[at]` withdrawn into `libowners`

### Access mode
- [x] `chmod`
- [x] `fchmod`
- [x] `fchmodat`

**Comment by treeswift** [comment]
…fcntl, notifications (Toybox uses `poll()`), flock, chown.

**Comment by treeswift** [comment]
fcntl, flock, `HANDLE` registration

**Comment by treeswift** [comment]
fcntl(status), fcntl(locks), pure C path resolution API

**Comment by treeswift** [comment]
TODO/MOREINFO: support idiomatic

```
ULONG mode = 1;  // O_NONBLOCK
ioctlsocket(sock, FIONBIO, &mode);
```
